/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.treina.jobs;

/**
 * Local home interface for AcaoImportanteJob.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface AcaoImportanteJobLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/AcaoImportanteJobLocal";
   public static final String JNDI_NAME="AcaoImportanteJobLocal";

   public br.com.sankhya.treina.jobs.AcaoImportanteJobLocal create()
      throws javax.ejb.CreateException;

}

