/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.treina.jobs;

/**
 * Local interface for AcaoImportanteJob.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface AcaoImportanteJobLocal
   extends javax.ejb.EJBLocalObject
{

   public void onSchedule(  ) throws java.lang.Exception, br.com.sankhya.modelcore.MGEModelException;

   public java.lang.String getScheduleConfig(  ) throws java.lang.Exception;

}
