/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.acompfrete.services;

/**
 * Remote interface for LancamentoFinancFreteSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface LancamentoFinancFreteSP
   extends javax.ejb.EJBObject
{

   public void importarArquivo( br.com.sankhya.ws.ServiceContext ctx )
      throws br.com.sankhya.modelcore.MGEModelException, java.rmi.RemoteException;

   public void lancarFinanceiro( br.com.sankhya.ws.ServiceContext ctx )
      throws br.com.sankhya.modelcore.MGEModelException, java.rmi.RemoteException;

   public void executarSelect( br.com.sankhya.ws.ServiceContext ctx )
      throws br.com.sankhya.modelcore.MGEModelException, java.rmi.RemoteException;

   public void executarInsert( br.com.sankhya.ws.ServiceContext ctx )
      throws br.com.sankhya.modelcore.MGEModelException, java.rmi.RemoteException;

   public void executarJsonArray( br.com.sankhya.ws.ServiceContext ctx )
      throws br.com.sankhya.modelcore.MGEModelException, java.rmi.RemoteException;

   public void executarUpdate( br.com.sankhya.ws.ServiceContext ctx )
      throws br.com.sankhya.modelcore.MGEModelException, java.rmi.RemoteException;

   public void executarDelete( br.com.sankhya.ws.ServiceContext ctx )
      throws br.com.sankhya.modelcore.MGEModelException, java.rmi.RemoteException;

   public void executarNativeSql( br.com.sankhya.ws.ServiceContext ctx )
      throws br.com.sankhya.modelcore.MGEModelException, java.rmi.RemoteException;

}
