/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.acompfrete.services;

/**
 * Session layer for LancamentoFinancFreteSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public class LancamentoFinancFreteSPSession
   extends br.com.sankhya.acompfrete.services.LancamentoFinancFreteSPBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {

   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
   }

   public void unsetSessionContext() 
   {
   }

   public void ejbRemove() 
   {
   }

   public void ejbCreate() throws javax.ejb.CreateException
   {
   }

}
