/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.acompfrete.services;

/**
 * Home interface for LancamentoNotasFreteSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface LancamentoNotasFreteSPHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LancamentoNotasFreteSP";
   public static final String JNDI_NAME="br/com/sankhya/acompfrete/services/LancamentoNotasFreteSP";

   public br.com.sankhya.acompfrete.services.LancamentoNotasFreteSP create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
