/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.acompfrete.services;

/**
 * Remote interface for LancamentoNotasFreteSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface LancamentoNotasFreteSP
   extends javax.ejb.EJBObject
{

   public void lancarNota( br.com.sankhya.ws.ServiceContext ctx )
      throws br.com.sankhya.modelcore.MGEModelException, java.rmi.RemoteException;

}
