/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.acompfrete.services;

/**
 * Home interface for LancamentoFinancFreteSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface LancamentoFinancFreteSPHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/LancamentoFinancFreteSP";
   public static final String JNDI_NAME="br/com/sankhya/acompfrete/services/LancamentoFinancFreteSP";

   public br.com.sankhya.acompfrete.services.LancamentoFinancFreteSP create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
