/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.acompfrete.services;

/**
 * Local home interface for TreinamentoJob.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TreinamentoJobLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TreinamentoJobLocal";
   public static final String JNDI_NAME="TreinamentoJobLocal";

   public br.com.sankhya.acompfrete.services.TreinamentoJobLocal create()
      throws javax.ejb.CreateException;

}

