/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.acompfrete.services;

/**
 * Local interface for TreinamentoJob.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TreinamentoJobLocal
   extends javax.ejb.EJBLocalObject
{

   public void onSchedule(  ) throws java.lang.Exception, br.com.sankhya.modelcore.MGEModelException;

}
