/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.gerenciafretes.services;

/**
 * Remote interface for GerenciaFretesSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GerenciaFretesSP
   extends javax.ejb.EJBObject
{

   public void inserirFrete( br.com.sankhya.ws.ServiceContext sctx )
      throws java.rmi.RemoteException;

   public void dividirValor( br.com.sankhya.ws.ServiceContext sctx )
      throws java.rmi.RemoteException;

   public void duplicarFrete( br.com.sankhya.ws.ServiceContext sctx )
      throws java.rmi.RemoteException;

}
