/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.gerenciafretes.services;

/**
 * Home interface for GerenciaFretesSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GerenciaFretesSPHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GerenciaFretesSP";
   public static final String JNDI_NAME="br/com/gerenciafretes/services/GerenciaFretesSP";

   public br.com.gerenciafretes.services.GerenciaFretesSP create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
