/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.sankhya.treina.services;

/**
 * Home interface for TreinamentoSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface TreinamentoSPHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/TreinamentoSP";
   public static final String JNDI_NAME="br/com/sankhya/treina/services/TreinamentoSP";

   public br.com.sankhya.treina.services.TreinamentoSP create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
